# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_twittermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='login.UserProfile')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='login.UserProfile')),
            ],
        ),
    ]
