# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_followingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittermodel',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
