# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_twittermodel_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=100)),
                ('Tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TwitterModel')),
            ],
        ),
    ]
