# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_twitcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserProfile')),
                ('Tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TwitterModel')),
            ],
        ),
        migrations.AddField(
            model_name='twitcomment',
            name='CommnetBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.UserProfile'),
        ),
    ]
