# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190123_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='twitlike',
            unique_together=set([('Tweet', 'LikedBy')]),
        ),
    ]
