# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190123_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitcomment',
            old_name='CommnetBy',
            new_name='CommentBy',
        ),
        migrations.AlterUniqueTogether(
            name='followingmodel',
            unique_together=set([('User', 'Following')]),
        ),
    ]
